export const HOME_FILTRED_BY_PAYMENT_STATUS = "HOME_FILTRED_BY_PAYMENT_STATUS";
export const HOME_FILTRED_BY_PAYMENT_DATE = "HOME_FILTRED_BY_PAYMENT_STATUS";
export const HOME_FILTRED_BY_PAYMENT_SUM = "HOME_FILTRED_BY_PAYMENT_STATUS";

export const HOME_SORTED_BY_PAYMENT_STATUS = "HOME_FILTRED_BY_PAYMENT_STATUS";
export const HOME_SORTED_BY_PAYMENT_DATE = "HOME_FILTRED_BY_PAYMENT_STATUS";
export const HOME_SORTED_BY_PAYMENT_SUM = "HOME_FILTRED_BY_PAYMENT_STATUS";

export const HOME_CHANGE_FIND_FIELD = "HOME_CHANGE_FIND_FIELD";

// Экшен для выбора платежа
// const HOME_SELECT_PAYMENT ="HOME_SELECT_PAYMENT";

// возможно нужно поменять keyword на что то другое
export const setFindKeyword = keyword => ({
  type: HOME_CHANGE_FIND_FIELD,
  payload: keyword
});
