const HOME_FILTRED_BY_PAYMENT_STATUS ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_FILTRED_BY_PAYMENT_DATE ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_FILTRED_BY_PAYMENT_SUM ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_FILTRED_BY_PAYMENT_STATUS ="HOME_FILTRED_BY_PAYMENT_STATUS";

const HOME_SORTED_BY_PAYMENT_STATUS ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_SORTED_BY_PAYMENT_DATE ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_SORTED_BY_PAYMENT_SUM ="HOME_FILTRED_BY_PAYMENT_STATUS";
const HOME_SORTED_BY_PAYMENT_STATUS ="HOME_FILTRED_BY_PAYMENT_STATUS";

const HOME_CHANGE_FIND_FIELD = "HOME_CHANGE_FIND_FIELD";